### ISSUE TITLE
Some problem in Functions.py

### ISSUE THREAD

**Issue by lizzle-lei** [lphLeo/FaiREE#1]
In the Functions.py file, what do p1, p_y0, p_y1, te_10, and te_11 mean? I am currently unable to run the Functions.py successfully. Could you give some advice? Thank you!
![image](https://github.com/lphLeo/FaiREE/assets/46184675/8d79b6c7-10ec-4c7b-8ff6-21a37ca27624)

**Comment by lphLeo** [comment]
Thank you for the question! Functions.py includes the functions that are needed in running other .py files, such as FaiREE_EOO.py, so you don't actually need to run Functions.py. It's imported in other .py files. Here are the notations: p1 = P(A=1), p_y0 = P(Y=1|A=0), p_y1 = P(Y=1|A=1). te_10 is the scores of the original classifier on the test data with Y=1, A=0; te_11 is the scores of the original classifier on the test data with Y=1, A=1. You can find the detailed definitions of notations in Section 2 of the paper.

**Comment by lizzle-lei** [comment]
Thank you very much!
